import type { BlogPost, BlogPostPreview } from '@/modules/blog/types'

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: '更适合北大宝宝体质的 xv6 OS Lab 踩坑记 - Part8',
    excerpt: '北京大学 2025 年秋季学期操作系统/OS Lab Part 8',
    date: '2026-01-12',
    datetime: '2026-01-11T23:00:01.000Z',
    tags: ['操作系统', 'xv6', 'pku'],
    readTime: '17 min read',
    lang: '中文',
    href: '#',
  },
  {
    id: 2,
    title: '更适合北大宝宝体质的 xv6 OS Lab 踩坑记 - Part6',
    excerpt: '北京大学 2025 年秋季学期操作系统/OS Lab Part 6',
    date: '2026-01-12',
    datetime: '2026-01-11T23:00:00.000Z',
    tags: ['操作系统', 'xv6', 'pku'],
    readTime: '26 min read',
    lang: '中文',
    href: '#',
  },
  {
    id: 3,
    title: '如何降级 iOS / iPadOS App',
    excerpt: '唉，商业化，原本好好的 App 就这么被塞满了广告',
    date: '2025-11-29',
    datetime: '2025-11-29',
    tags: ['ics', 'pku'],
    readTime: '3 min read',
    lang: '中文',
    href: '#',
  },
  {
    id: 4,
    title: '从零开始配置 Windows',
    excerpt: '环境配置什么的真是烦死辣！',
    date: '2025-11-26',
    datetime: '2025-11-26',
    tags: ['windows', 'shell', 'wsl', 'initialize'],
    readTime: '7 min read',
    lang: '中文',
    href: '#',
  },
  {
    id: 5,
    title: 'PKU Art - 简洁优雅的教学网美化方案',
    excerpt: 'PKU Art 是一个美化北京大学教学网的浏览器扩展与用户样式表，提供优雅、现代化的视觉体验。',
    date: '2025-11-24',
    datetime: '2025-11-24',
    tags: ['pku', 'css', 'javascript'],
    readTime: '16 min read',
    lang: '中文',
    href: '#',
  },
  {
    id: 6,
    title: '更适合北大宝宝体质的 xv6 OS Lab 踩坑记 - Part5',
    excerpt: '北京大学 2025 年秋季学期操作系统/OS Lab Part 5',
    date: '2025-11-23',
    datetime: '2025-11-23',
    tags: ['操作系统', 'xv6', 'pku'],
    readTime: '22 min read',
    lang: '中文',
    href: '#',
  },
  {
    id: 7,
    title: '从零开始配置 Mac',
    excerpt: '环境配置什么的真是烦死辣！',
    date: '2025-11-12',
    datetime: '2025-11-12',
    tags: ['mac', 'initialize'],
    readTime: '13 min read',
    lang: '中文',
    href: '#',
  },
  {
    id: 8,
    title: 'PKU VPN 3 - 用校内服务器实现 PKU 内网和 Clash/Surge 兼容使用',
    excerpt: '我真没想到这玩意还会出第三篇',
    date: '2025-11-11',
    datetime: '2025-11-11',
    tags: ['clash', 'surge', 'pku', 'vpn'],
    readTime: '9 min read',
    lang: '中文',
    href: '#',
  },
]

export const BLOG_POST_PREVIEWS: BlogPostPreview[] = [
  {
    id: 1,
    title: '从医学到AI：我的跨界学习之路',
    date: '2024-01-15',
    datetime: '2024-01-15',
  },
  {
    id: 2,
    title: 'PyTorch实战：从零开始构建LLM',
    date: '2024-01-10',
    datetime: '2024-01-10',
  },
  {
    id: 3,
    title: 'Minecraft中的编程思维',
    date: '2024-01-05',
    datetime: '2024-01-05',
  },
  {
    id: 4,
    title: '双学位的挑战与收获',
    date: '2023-12-28',
    datetime: '2023-12-28',
  },
]

export const BLOG_POSTS_TOTAL = 85
export const BLOG_POSTS_TOTAL_PAGES = 11
