/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CapabilityTable: typeof import('./../components/site/CapabilityTable.vue')['default']
    ChatComposer: typeof import('@/components/chat/ChatComposer.vue')['default']
    ChatSidebar: typeof import('@/components/chat/ChatSidebar.vue')['default']
    ChatStream: typeof import('@/components/chat/ChatStream.vue')['default']
    EditorialWorkspace: typeof import('./../components/management/EditorialWorkspace.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FeatureGrid: typeof import('./../components/site/FeatureGrid.vue')['default']
    HeroSection: typeof import('./../components/site/HeroSection.vue')['default']
    LoginDialog: typeof import('./../components/ui/LoginDialog.vue')['default']
    MenuPanel: typeof import('./../components/site/MenuPanel.vue')['default']
    ModuleCard: typeof import('./../components/ModuleCard.vue')['default']
    ModuleGrid: typeof import('./../components/ModuleGrid.vue')['default']
    OverviewPanel: typeof import('./../components/OverviewPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionIntro: typeof import('./../components/site/SectionIntro.vue')['default']
    SiteFooter: typeof import('./../components/site/SiteFooter.vue')['default']
    SpotlightSection: typeof import('./../components/site/SpotlightSection.vue')['default']
    StoryTimeline: typeof import('./../components/site/StoryTimeline.vue')['default']
  }
}
