/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./../components/blog/AboutSection.vue')['default']
    ChatComposer: typeof import('./../components/ai/ChatComposer.vue')['default']
    ChatSidebar: typeof import('./../components/ai/ChatSidebar.vue')['default']
    ChatStream: typeof import('./../components/ai/ChatStream.vue')['default']
    EducationSection: typeof import('./../components/blog/EducationSection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FeatureGrid: typeof import('./../components/site/FeatureGrid.vue')['default']
    GalleryLightbox: typeof import('./../components/site/GalleryLightbox.vue')['default']
    HeroSection: typeof import('./../components/site/HeroSection.vue')['default']
    LoginDialog: typeof import('./../components/ui/LoginDialog.vue')['default']
    MenuPanel: typeof import('./../components/site/MenuPanel.vue')['default']
    PostsSection: typeof import('./../components/blog/PostsSection.vue')['default']
    PriceResult: typeof import('./../components/price/PriceResult.vue')['default']
    ProfileAccessibilitySection: typeof import('./../components/dashboard/ProfileAccessibilitySection.vue')['default']
    ProfileAccountSection: typeof import('./../components/dashboard/ProfileAccountSection.vue')['default']
    ProfileAppearanceSection: typeof import('./../components/dashboard/ProfileAppearanceSection.vue')['default']
    ProfileNotificationsSection: typeof import('./../components/dashboard/ProfileNotificationsSection.vue')['default']
    ProfilePublicProfileSection: typeof import('./../components/dashboard/ProfilePublicProfileSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionIntro: typeof import('./../components/site/SectionIntro.vue')['default']
    SettingsSidebar: typeof import('./../components/dashboard/SettingsSidebar.vue')['default']
    SettingsWorkspaceShell: typeof import('./../components/dashboard/SettingsWorkspaceShell.vue')['default']
    SiteFooter: typeof import('./../components/site/SiteFooter.vue')['default']
    SkillsSection: typeof import('./../components/blog/SkillsSection.vue')['default']
    SpotlightSection: typeof import('./../components/site/SpotlightSection.vue')['default']
    StoryTimeline: typeof import('./../components/site/StoryTimeline.vue')['default']
  }
}
