/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CapabilityTable: typeof import('./../../components/site/CapabilityTable.vue')['default']
    ChatComposer: typeof import('./../../components/chat/ChatComposer.vue')['default']
    ChatSidebar: typeof import('./../../components/chat/ChatSidebar.vue')['default']
    ChatStream: typeof import('./../../components/chat/ChatStream.vue')['default']
    EditorialWorkspace: typeof import('./../../components/management/EditorialWorkspace.vue')['default']
    FeatureGrid: typeof import('./../../components/site/FeatureGrid.vue')['default']
    GalleryLightbox: typeof import('./../../components/site/GalleryLightbox.vue')['default']
    HeroSection: typeof import('./../../components/site/HeroSection.vue')['default']
    LoginDialog: typeof import('./../../components/ui/LoginDialog.vue')['default']
    MenuPanel: typeof import('./../../components/site/MenuPanel.vue')['default']
    ModuleCard: typeof import('./../../components/management/ModuleCard.vue')['default']
    ModuleGrid: typeof import('./../../components/management/ModuleGrid.vue')['default']
    OverviewPanel: typeof import('./../../components/management/OverviewPanel.vue')['default']
    PriceResult: typeof import('./../../components/price/PriceResult.vue')['default']
    ProfileAccessibilitySection: typeof import('./../../components/profile/ProfileAccessibilitySection.vue')['default']
    ProfileAccountSection: typeof import('./../../components/profile/ProfileAccountSection.vue')['default']
    ProfileAppearanceSection: typeof import('./../../components/profile/ProfileAppearanceSection.vue')['default']
    ProfileNotificationsSection: typeof import('./../../components/profile/ProfileNotificationsSection.vue')['default']
    ProfilePublicProfileSection: typeof import('./../../components/profile/ProfilePublicProfileSection.vue')['default']
    ProfileSettingsSidebar: typeof import('./../../components/profile/ProfileSettingsSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionIntro: typeof import('./../../components/site/SectionIntro.vue')['default']
    SettingsWorkspaceShell: typeof import('./../../components/layout/SettingsWorkspaceShell.vue')['default']
    SiteFooter: typeof import('./../../components/site/SiteFooter.vue')['default']
    SpotlightSection: typeof import('./../../components/site/SpotlightSection.vue')['default']
    StoryTimeline: typeof import('./../../components/site/StoryTimeline.vue')['default']
  }
}
